/** Protestant canon order 1..66: USFM id + display name. */
export const USFM_LIST = [
  { id: "GEN", n: "Genesis" },
  { id: "EXO", n: "Exodus" },
  { id: "LEV", n: "Leviticus" },
  { id: "NUM", n: "Numbers" },
  { id: "DEU", n: "Deuteronomy" },
  { id: "JOS", n: "Joshua" },
  { id: "JDG", n: "Judges" },
  { id: "RUT", n: "Ruth" },
  { id: "1SA", n: "1 Samuel" },
  { id: "2SA", n: "2 Samuel" },
  { id: "1KI", n: "1 Kings" },
  { id: "2KI", n: "2 Kings" },
  { id: "1CH", n: "1 Chronicles" },
  { id: "2CH", n: "2 Chronicles" },
  { id: "EZR", n: "Ezra" },
  { id: "NEH", n: "Nehemiah" },
  { id: "EST", n: "Esther" },
  { id: "JOB", n: "Job" },
  { id: "PSA", n: "Psalms" },
  { id: "PRO", n: "Proverbs" },
  { id: "ECC", n: "Ecclesiastes" },
  { id: "SNG", n: "Song of Solomon" },
  { id: "ISA", n: "Isaiah" },
  { id: "JER", n: "Jeremiah" },
  { id: "LAM", n: "Lamentations" },
  { id: "EZK", n: "Ezekiel" },
  { id: "DAN", n: "Daniel" },
  { id: "HOS", n: "Hosea" },
  { id: "JOL", n: "Joel" },
  { id: "AMO", n: "Amos" },
  { id: "OBA", n: "Obadiah" },
  { id: "JON", n: "Jonah" },
  { id: "MIC", n: "Micah" },
  { id: "NAM", n: "Nahum" },
  { id: "HAB", n: "Habakkuk" },
  { id: "ZEP", n: "Zephaniah" },
  { id: "HAG", n: "Haggai" },
  { id: "ZEC", n: "Zechariah" },
  { id: "MAL", n: "Malachi" },
  { id: "MAT", n: "Matthew" },
  { id: "MRK", n: "Mark" },
  { id: "LUK", n: "Luke" },
  { id: "JHN", n: "John" },
  { id: "ACT", n: "Acts" },
  { id: "ROM", n: "Romans" },
  { id: "1CO", n: "1 Corinthians" },
  { id: "2CO", n: "2 Corinthians" },
  { id: "GAL", n: "Galatians" },
  { id: "EPH", n: "Ephesians" },
  { id: "PHP", n: "Philippians" },
  { id: "COL", n: "Colossians" },
  { id: "1TH", n: "1 Thessalonians" },
  { id: "2TH", n: "2 Thessalonians" },
  { id: "1TI", n: "1 Timothy" },
  { id: "2TI", n: "2 Timothy" },
  { id: "TIT", n: "Titus" },
  { id: "PHM", n: "Philemon" },
  { id: "HEB", n: "Hebrews" },
  { id: "JAS", n: "James" },
  { id: "1PE", n: "1 Peter" },
  { id: "2PE", n: "2 Peter" },
  { id: "1JN", n: "1 John" },
  { id: "2JN", n: "2 John" },
  { id: "3JN", n: "3 John" },
  { id: "JUD", n: "Jude" },
  { id: "REV", n: "Revelation" },
];

export const BNUMBER_TO_USFM = Object.fromEntries(USFM_LIST.map((b, i) => [i + 1, b.id]));

export const USFM_BY_ID = Object.fromEntries(USFM_LIST.map((b) => [b.id, b]));
